name: Test testflo

on:
  # Trigger on push or pull request events for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allow running the workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

permissions: {}

jobs:

  tests:

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        include:
          # test on Ubuntu with OpenMPI
          - NAME: Ubuntu OpenMPI
            OS: ubuntu-latest
            MPI: openmpi
            PIXI_ENV: default

          # test on Ubuntu with MPICH
          - NAME: Ubuntu MPICH
            OS: ubuntu-latest
            MPI: mpich
            PIXI_ENV: mpich

          # test on MacOS with OpenMPI
          - NAME: MacOS OpenMPI
            OS: macos-latest
            MPI: openmpi
            PIXI_ENV: default

          # test on MacOS with MPICH
          - NAME: MacOS MPICH
            OS: macos-latest
            MPI: mpich
            PIXI_ENV: mpich

    runs-on: ${{ matrix.OS }}

    name: ${{ matrix.NAME }}

    defaults:
      run:
        shell: bash -l {0}

    steps:

      - name: Checkout code
        uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.7.0
        with:
          pixi-version: v0.29.0
          environments: ${{ matrix.PIXI_ENV }}

      - name: Install testflo
        run: |
          pixi run -e ${{ matrix.PIXI_ENV }} pip install -e .

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      #
      # To access the terminal through the web-interface:
      #    1. Click on the web-browser link printed out in this action from the github
      #       workflow terminal
      #    2. Press cntrl + c in the new tab that opens up to reveal the terminal
      #    3. To activate the conda environment run:
      #        $ source $CONDA/etc/profile.d/conda.sh
      #        $ conda activate test
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Run tests
        run: |
          cd $HOME

          pixi run -e ${{ matrix.PIXI_ENV }} testflo --skip_dir=pytest_tests testflo.tests -vs --show_skipped --durations=5 --durations-min=0 --deprecations_report dep.txt || RC=$?

          if [[ $RC -ne 1 ]]; then
            echo "Expected some tests to fail."
            exit 1
          fi

          if [[ ! -n `grep "Ran 26 tests" testflo_report.out` ]]; then
            echo "Expected 26 tests."
            exit 26
          fi

          if [[ ! -n `grep "Passed:  7" testflo_report.out` ]]; then
            echo "Expected 7 tests to pass."
            exit 7
          fi

          if [[ ! -n `grep "Failed:  8" testflo_report.out` ]]; then
            echo "Expected 8 tests to fail."
            exit 8
          fi

          if [[ ! -n `grep "Skipped: 11" testflo_report.out` ]]; then
            echo "Expected 11 tests to be skipped."
            exit 11
          fi

          grep "Deprecations Report" dep.txt
          rm dep.txt

      - name: Run tests in serial
        run: |
          cd $HOME

          pixi run -e ${{ matrix.PIXI_ENV }} testflo --skip_dir=pytest_tests testflo.tests -n 1 -vs --show_skipped --durations=5 --durations-min=0 --deprecations_report dep.txt || RC=$?

          if [[ $RC -ne 1 ]]; then
            echo "Expected some tests to fail."
            exit 1
          fi

          if [[ ! -n `grep "Ran 26 tests using 1 processes" testflo_report.out` ]]; then
            echo "Expected 26 tests on one process."
            exit 26
          fi

          if [[ ! -n `grep "Passed:  7" testflo_report.out` ]]; then
            echo "Expected 7 tests to pass."
            exit 7
          fi

          if [[ ! -n `grep "Failed:  8" testflo_report.out` ]]; then
            echo "Expected 8 tests to fail."
            exit 8
          fi

          if [[ ! -n `grep "Skipped: 11" testflo_report.out` ]]; then
            echo "Expected 11 tests to be skipped."
            exit 11
          fi

          grep "Deprecations Report" dep.txt
          rm dep.txt

      - name: Test pytest plugin
        env:
          PIXI_ENV: pytest${{ matrix.PIXI_ENV == 'mpich' && '-mpich' || '' }}
        run: |
          cd $HOME

          pixi run -e $PIXI_ENV pytest $GITHUB_WORKSPACE/testflo/tests/pytest_tests/test_pytest_plugin.py -n auto --import-mode=importlib
          pixi run -e $PIXI_ENV pytest $GITHUB_WORKSPACE/testflo/tests/pytest_tests/test_pytest_plugin.py -n auto --mpi-workers=2 --import-mode=importlib
          pixi run -e $PIXI_ENV pytest $GITHUB_WORKSPACE/testflo/tests/pytest_tests/test_pytest_plugin.py -n auto --nompi --import-mode=importlib

      - name: Notify slack of failure
        uses: act10ns/slack@v2.0.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          status: ${{ job.status }}
        if: failure()


